apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-go
  template:
    metadata:
      labels:
        app: guestbook-go
    spec:
      containers:
      - name: guestbook-go
        image: deepanshu2000/guestbook-go:latest
        ports:
        - containerPort: 8080