name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
    # Only run when the commit message contains `BUILD_CONTAINER_IMAGE`
    # This condition is defined in the job level
  pull_request:
    types:
      - closed
    branches:
      - main  # Trigger the workflow when a PR is merged into the main branch

jobs:
  build:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged == true ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build the Go application
      run: |
        go mod download
        CGO_ENABLED=0 GOOS=linux go build -o main .

    - name: Build Docker image
      run: docker build -t deepanshu2000/guestbook-go:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push deepanshu2000/guestbook-go:latest